const fs = require("fs").promises
const path = require("path")
const { scrapeCourseDescription } = require("../helpers/courses/course_scraper")

test("Autogenerated course info file exists", async () => {
  console.log(__dirname)
  const d = await fs.readFile(
    path.join(
      __dirname,
      "..",
      "src",
      "pages",
      "courses",
      "autogenerated_course_info.json"
    )
  )
  expect(d.courses)
})

test.skip("Properly scrapes Pitt SCI website for course info", async () => {
  const cs445 = await scrapeCourseDescription(
    "http://courses.sci.pitt.edu/courses/view/CS-0445"
  )
  expect(cs445.credits).toBe(3)
  expect(cs445.description)
})
