import COURSE_LIST from "../../data/autogenerated_course_info.json"
import { cleanCourseId } from "../../utils/course-namer"
import React from "react"
import { Link } from "gatsby"

const coursesWithWikiPages = COURSE_LIST.courses.reduce((acc, current) => {
  acc[current.id] = true
  if (current.replaces) {
    acc[current.replaces] = true
  }
  return acc
}, {})

export default function CourseLink({ id }) {
  const cleanedId = cleanCourseId(id)
  if (coursesWithWikiPages[id]) {
    return <Link to={`/courses/${id}`}>{cleanedId}</Link>
  } else {
    return (
      <a
        target="_blank"
        rel="noopener noreferrer"
        href={`https://www.google.com/search?q=${cleanedId} pitt`}
      >
        {cleanedId}
      </a>
    )
  }
}
